sequenceDiagram
  rect rgb(191, 223, 255)
    note over Requester,Provider: Request a new template
    Requester->>+Provider: gettmplt [round=0 basis_id]
    note left of Provider: Generate new template
    Provider->>-Requester: tmplt [round=0 id tip nonce basis_id/idx/posns sketches]
  end
  rect rgb(255, 223, 191)
    note over Requester,Provider: Reconcile shortids
    loop
      Requester->>Provider: gettmplt [round=1..4 id masks]
      Provider->>Requester: tmplt [round=1..4 id basis_idx masks shortids sketches]
    end
  end
  rect rgb(191, 223, 255)
    note over Requester,Provider: Resolve shortids
  end
  rect rgb(255, 223, 191)
    note over Requester,Provider: Obtain missing transactions
    opt
      Requester->>Provider: gettmplttxn [id shortidposns]
      Provider->>Requester: tmplttxn [id txs...]
      Provider->>Requester: tmplttxn [id txs...]
      Provider->>Requester: tmplttxn [id txs...]
    end
  end
    note right of Requester: Store txs from template
    note right of Requester: Attempt to add new txs to mempool
